version: '2'

services:

    proxy:
        container_name: proxy
        image: jwilder/nginx-proxy
        ports:
            - 8080:80/tcp
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        environment:
            - PGID=${PGID}
            - PUID=${PUID}

    plex:
        container_name: plex
        image: linuxserver/plex
        ports:
            - 32400:32400/tcp
            - 33400:33400/tcp
            - 3005:3005/tcp
            - 8324:8324/tcp
            - 32469:32469/tcp
            - 1900:1900/udp
            - 32410:32410/udp
            - 32412:32412/udp
            - 32413:32413/udp
            - 32414:32414/udp
        hostname: homer
        volumes:
            - ${PLEX_CONFIG_DIR}:/config
            - ${MOVIES_DIR}:/movies
            - ${TRANSCODE_DIR}:/transcode
            - ${TV_DIR}:/tv
        environment:
            - ADVERTISE_IP=http://192.168.1.222:32400/
            - ALLOWED_NETWORKS=192.168.1.0/24
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=America/New_York
            - VERSION=latest
            - VIRTUAL_HOST=${PLEX_HOST}
            - VIRTUAL_PORT=32400

    radarr:
        container_name: radarr
        image: linuxserver/radarr
        ports:
            - 7878:7878/tcp
        volumes:
            - ${RADARR_CONFIG_DIR}:/config
            - ${DOWNLOADS_DIR}:/downloads
            - ${MOVIES_DIR}:/movies
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=America/New_York
            - VIRTUAL_HOST=${RADARR_HOST}

    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr
        ports:
            - 8989:8989/tcp
        volumes:
            - ${SONARR_CONFIG_DIR}:/config
            - ${DOWNLOADS_DIR}:/downloads
            - ${TV_DIR}:/tv
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=America/New_York
            - VIRTUAL_HOST=${SONARR_HOST}

    transmission:
        container_name: transmission
        image: linuxserver/transmission
        ports:
            - 9091:9091/tcp
            - 51413:51413/tcp
        volumes:
            - ${TRANSMISSION_CONFIG_DIR}:/config
            - ${DOWNLOADS_DIR}:/downloads
            - ${WATCH_DIR}:/watch
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=America/New_York
            - VIRTUAL_HOST=${TRANSMISSION_HOST}
            - VIRTUAL_PORT=9091

    cardigann:
        container_name: cardigann
        image: linuxserver/cardigann
        ports:
            - 5060:5060/tcp
        volumes:
            - ${CARDIGANN_CONFIG_DIR}:/config
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=America/New_York
            - VIRTUAL_HOST=${CARDIGANN_HOST}
            - VIRTUAL_PORT=5060

    jackett:
        container_name: jackett
        image: linuxserver/jackett
        ports:
            - 9117:9117/tcp
        volumes:
            - ${JACKETT_CONFIG_DIR}:/config
            - /tmp/jackett:/downloads
            - /etc/localtime:/etc/localtime:ro
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=America/New_York
