version: '2'

services:

    proxy:
        container_name: proxy
        image: jwilder/nginx-proxy
        ports:
            - 8080:80/tcp
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        environment:
            - PGID=${PGID}
            - PUID=${PUID}

    plex:
        container_name: plex
        image: linuxserver/plex
        network_mode: host
        hostname: homer
        volumes:
            - ${PLEX_CONFIG_DIR}:/config
            - ${MOVIES_DIR}:/movies
            - ${TRANSCODE_DIR}:/transcode
            - ${TV_DIR}:/tv
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=America/New_York
            - VERSION=latest

    radarr:
        container_name: radarr
        image: linuxserver/radarr
        ports:
            - 7878:7878/tcp
        volumes:
            - ${RADARR_CONFIG_DIR}:/config
            - ${DOWNLOADS_DIR}:/downloads
            - ${MOVIES_DIR}:/movies
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=America/New_York
            - VIRTUAL_HOST=${RADARR_HOST}

    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr
        ports:
            - 8989:8989/tcp
        volumes:
            - ${SONARR_CONFIG_DIR}:/config
            - ${DOWNLOADS_DIR}:/downloads
            - ${TV_DIR}:/tv
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=America/New_York
            - VIRTUAL_HOST=${SONARR_HOST}

    transmission:
        container_name: transmission
        image: linuxserver/transmission
        ports:
            - 9091:9091/tcp
            - 51413:51413/tcp
        volumes:
            - ${TRANSMISSION_CONFIG_DIR}:/config
            - ${DOWNLOADS_DIR}:/downloads
            - ${WATCH_DIR}:/watch
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=America/New_York
            - VIRTUAL_HOST=${TRANSMISSION_HOST}
            - VIRTUAL_PORT=9091

    jackett:
        container_name: jackett
        image: linuxserver/jackett
        ports:
            - 9117:9117/tcp
        volumes:
            - ${JACKETT_CONFIG_DIR}:/config
            - /tmp/jackett:/downloads
            - /etc/localtime:/etc/localtime:ro
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=America/New_York
            - VIRTUAL_HOST=${JACKETT_HOST}
            - VIRTUAL_PORT=9117

    organizr:
        container_name: organizr
        image: linuxserver/organizr
        ports:
            - 9983:80/tcp
        volumes:
            - ${ORGANIZR_CONFIG_DIR}:/config
            - /tmp/jackett:/downloads
            - /etc/localtime:/etc/localtime:ro
        environment:
            - PGID=${PGID}
            - PUID=${PUID}
            - TZ=America/New_York
            - VIRTUAL_HOST=${ORGANIZR_HOST}
